# Generated by Django 5.1.4 on 2024-12-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uffanunciaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='chat',
        ),
    ]
