# Generated by Django 5.1.2 on 2024-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uffanunciaapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anuncio",
            name="local",
            field=models.CharField(
                choices=[
                    ("niteroi", "Niterói"),
                    ("rio de janeiro", "Rio de Janeiro"),
                    ("sao goncalo", "São Gonçalo"),
                    ("oceanica", "Região Oceânica"),
                    ("outros", "Outro"),
                ],
                default="outros",
                max_length=16,
            ),
        ),
    ]
