# Generated by Django 5.1.4 on 2024-12-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uffanunciaapp', '0002_anuncio_local'),
        ('uffanunciaapp', '0002_remove_avaliacao_chat'),
    ]

    operations = [
    ]
