# Generated by Django 5.1.2 on 2024-11-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uffanunciaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.CharField(choices=[('academico', 'Acadêmico'), ('alimentos', 'Alimentos'), ('moradia', 'Moraia'), ('outros', 'Outros')], default='outros', max_length=10),
        ),
    ]
