# Generated by Django 5.1.2 on 2024-11-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uffanunciaapp', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Chat Mensagem', 'verbose_name_plural': 'Chat Mensagens'},
        ),
    ]
